---
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ordering <- na.omit(tab[,c("location_name","location_code","msis_difference","norsyss_difference")])
setorder(ordering,-msis_difference)
ordering_msis <- as.character(unique(ordering$location_code))
setorder(ordering,-norsyss_difference)
ordering_norsyss <- as.character(unique(ordering$location_code))
```

## MSIS Alerts

```{r dataclean1, include=FALSE, results="hide"}
tab[,location_code:=factor(location_code, levels = ordering_msis)]
setorder(tab,location_code,variable)

location_codes <- ordering_msis[ordering_msis %in% location_code_msis]
```

```{r tabmsis, results="asis", echo=F}
areas_at_risk_ht(tab = tab[location_code %in% location_codes], yrwks = yrwks)
```

## NorSySS Alerts

```{r include=FALSE, results="hide"}
tab[,location_code:=factor(location_code, levels = ordering_norsyss)]
setorder(tab,location_code,variable)

location_codes <- ordering_norsyss[!ordering_norsyss %in% location_code_msis]
```

```{r, results="asis", echo=F}
areas_at_risk_ht(tab = tab[location_code %in% location_codes], yrwks = yrwks)
areas_at_risk_ht(tab = tab[location_code %in% location_codes[1:10]], yrwks = yrwks)
areas_at_risk_ht(tab[location_code %in% location_codes[11:20]], yrwks = yrwks)
areas_at_risk_ht(tab[location_code %in% location_codes[21:30]], yrwks = yrwks)
areas_at_risk_ht(tab[location_code %in% location_codes[31:40]], yrwks = yrwks)
areas_at_risk_ht(tab[location_code %in% location_codes[41:45]], yrwks = yrwks)
```

